"""
Django settings for OMIE project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4vi36^a!&ie++8%ir$0pvv@rv#^u4fob-%haw_)f2te9$jh3z*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.10', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.DatabaseSelectorMiddleware',  # Seleção de banco de dados
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OMIE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OMIE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # Banco para autenticação Django
    },
    'benjamin': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'core' / 'backup_com_xml' / 'benjamin.db',
    },
    'casa_da_logistica': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'core' / 'backup_com_xml' / 'casa_da_logistica.db',
    },
    'cdg': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'core' / 'backup_com_xml' / 'cdg.db',
    },
    'criarmais': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'core' / 'backup_com_xml' / 'criarmais.db',
    },
    'educa': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'core' / 'backup_com_xml' / 'educa.db',
    },
    'itamar': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'core' / 'backup_com_xml' / 'itamar.db',
    },
    'site': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'core' / 'backup_com_xml' / 'site.db',
    },
}

# Database router para múltiplos bancos
DATABASE_ROUTERS = ['core.routers.MultiDatabaseRouter']

# Nomes amigáveis dos bancos para exibição
DATABASE_NAMES = {
    'benjamin': 'Benjamin',
    'casa_da_logistica': 'Casa da Logística',
    'cdg': 'CDG',
    'criarmais': 'Criar Mais',
    'educa': 'Educa',
    'itamar': 'Itamar',
    'site': 'Site',
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
